### ISSUE TITLE
[Login] If email was not confirmed, recover password does not work

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#535]
Not sure if this is by design, but If I try to recover the password of an account that does not have the email confirmed, the email never arrives. Maybe we could inform the user that he needs to confirm the email before recovering ?

**Comment by tiagonmas** [comment]
another user just reported this.

**Comment by pmagno** [comment]
@tiagonmas 

I was checking the code, and I have found this:

![image](https://user-images.githubusercontent.com/3904030/171456900-de6da552-b89a-4cfa-8e8a-476d863abbdf.png)

As you can see when if the email is not confirmed,  the password reset is ignored.

I will just do some research to see if there are some know problems by disabling this check. If no security problems appear, I will create the merge request.

**Comment by pmagno** [comment]
@tiagonmas 

after some research, does not make too much sense that we allow resetting the password without confirming the email. We need to have a clear distinction between the "real" user (who is able to login) and a "fake" user (possible attacker).

So, I would say, the best way is to show a message as you suggest.

**Comment by tiagonmas** [comment]
Agree! Maybe we can make a suggestion to the user to use [Resend confirmation email](https://www.alimentestaideia.pt/Identity/Account/ResendEmailConfirmation) in case he does not receive the confirmation email (because his email was not yet confirmed)

**Comment by tiagonmas** [comment]
your suggested layout looks great :)

**Comment by tiagonmas** [comment]
now in production. thanks @pmagno
