### ISSUE TITLE
Payment and Receipt management SAS platform

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#566]
Develop a multi tenant / SAS offering so that other non profit organizations can use the same functionalities of alimentestaideia to manage the payment of their donations, and the invoice creation.

Each tenant will also use Easypay payment gateway, with their own credentials.

Tracking specs in [Wiki](https://github.com/banco-alimentar/alimentestaideia.pt/wiki/Doar--Payment-and-Receipt-management-SAS-platform)

**Comment by guerrerotook** [comment]
The tenant now has two new properties that define the payment and invoicing strategy:

InvoicingStrategy
- SingleInvoiceTable: All invoices go to the same sequence and belong to the same legal entity.
- MultipleTablesPerFoodBank: Invoices are break into different food banks that they have their own sequence.

PaymentStrategy
- SharedPaymentProcessor: All payment processors are the same. EasyPay and PayPal.
- IndividualPaymentProcessorPerFoodBank: Each food bank has their own Easypay and Paypal instance to process payments.

**Comment by tiagonmas** [comment]
we should document this ... :)
