### ISSUE TITLE
Issue for exception (Easypay.Rest.Client.Client.ApiException)

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#626]
Only happening in dev when creating a new subscription.
json for request is in the exception details

**Operation Name:** POST /SubscriptionPayment

**Timestamp:** 2022-01-07T19:32:51.5520000Z

**Problem Id:** Easypay.Rest.Client.Client.ApiException

**Assembly:** Easypay.Rest.Client, Version=0.1.10.53993, Culture=neutral, PublicKeyToken=null

**Exception Type:** Easypay.Rest.Client.Client.ApiException

**Method:** Easypay.Rest.Client.Api.SubscriptionPaymentApi.SubscriptionPostWithHttpInfo

**Outer Exception Type:** Easypay.Rest.Client.Client.ApiException

**Outer Exception Message:** Error calling SubscriptionPost: {"status":"error","message":["Request body contains unknown field \"id\""]}

**Outer Exception Assembly:** Easypay.Rest.Client, Version=0.1.10.53993, Culture=neutral, PublicKeyToken=null

**Outer Exception Method:** Easypay.Rest.Client.Api.SubscriptionPaymentApi.SubscriptionPostWithHttpInfo

**Innermost Exception Type:** <undefined>

**Innermost Exception Message:** <undefined>

**Country or region:** Portugal

**State or province:** Lisbon

**City:** Oeiras

**Link:** https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22:%22f1b937fb-ca82-4eb6-a452-77af7a531344%22,%22ResourceGroup%22:%22AlimenteEstaIdeia%22,%22Name%22:%22alimentaestaideia-core%22%7D/DataModel/%7B%22eventId%22:%22bb7b8393-6ff0-11ec-94f5-281878137ace%22,%22timestamp%22:%222022-01-07T19:32:51.552Z%22%7D

**Comment by guerrerotook** [comment]
This has changed since we implemented the API in the nuget package. I'm going to remove the Id property from the library and publish a new version.

**Comment by guerrerotook** [comment]
Fixed the library in this commit, https://github.com/banco-alimentar/easypay-client-csharp/commit/9e7152a285ab32fdb2e863bed06903523e207af8 and updated the nuget package. Remove the ID property from the code.
