### ISSUE TITLE
[Multitenancy][WebSite] Integrate Liquid template engine into the donation website.

### ISSUE THREAD

**Issue by guerrerotook** [banco-alimentar/alimentestaideia.pt#659]
When tenants customize their own websites, instead of using the razor language features we will support Liquid templates. 

This task is to enable integration with Liquid templates and have a html5 editor in the same website.

**Comment by tiagonmas** [comment]
Hi Luis, are you still working on this or would this be a candidate for someone new to pickup ?

**Comment by tiagonmas** [comment]
does it make sense to keep this open @guerrerotook since it's a nice to have and we have not many people helping .)

**Comment by guerrerotook** [comment]
No, let's close it.
