### ISSUE TITLE
Wrong total basket value

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#667]
**Describe the bug**
A user is seeing a negative total when adding and removing products from the basket.
Edge on Windows 11, Portuguese cultural settings.
The issue only happens when adding and removing products that have decimals. It does not happen with round numbers.

**To Reproduce**
I could only reproduce it on the user PC (via skype). I could not yet repro locally.

**Expected behavior**

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/42462/171665690-46e62c48-cdcd-4253-9a18-00f527f78dc0.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version Latest

![image](https://user-images.githubusercontent.com/42462/171665886-7059353a-76a9-410c-98bb-c7fea3932fcf.png)

![image](https://user-images.githubusercontent.com/42462/171665932-4f251f35-fd7d-4bae-a11e-4f9f853e1022.png)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tiagonmas** [comment]
![image](https://user-images.githubusercontent.com/42462/171692552-4be96775-6644-48b0-9ac2-9a9db64fefc5.png)

**Comment by pmagno** [comment]
The amount of the basket was not updated because of the culture problem too (Locale), comma decimal separator.
