### ISSUE TITLE
Javascript errors

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#669]
**Describe the bug**
When loading the donation page, and checking the console devtools, we see several exceptions:

**Screenshots**
![image](https://user-images.githubusercontent.com/42462/171686163-170a8c52-80f0-4e25-93ac-5107ff9fdc2a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version Latest

**Comment by pmagno** [comment]
@tiagonmas 

The javascript code contains some errors:
![image](https://user-images.githubusercontent.com/3904030/171687817-397fa5b6-43f1-4fdf-b64a-0941c72b9a3d.png)

I have fixed that, but we need to decide which pixel facebook code (init) we should use.

![image](https://user-images.githubusercontent.com/3904030/171688041-23e27373-16d7-41c7-aedd-389b5e512457.png)

**Comment by tiagonmas** [comment]
ah! let's get rid of the first one and just keep the one that says it was created by me :)
