### ISSUE TITLE
Subscription expiration is set for 1 year and not 5

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#675]
**Describe the bug**
When we create a subscription the expire date is set for 1 year, but the code is set for 5

![image](https://user-images.githubusercontent.com/42462/179492255-30b3d836-0c2a-4ccd-8b69-00dfdf1090ce.png)

![image](https://user-images.githubusercontent.com/42462/179492402-8c1ae142-d648-41da-aee0-e721eedb31d3.png)

**Comment by guerrerotook** [comment]
This was an issue because I create the subscription with 5 years of expiration time, but in the database I have other code with other values. 

I modified the code to use the PaymentSubcription object to synchronize all this data.

**Comment by tiagonmas** [comment]
Can you update to 100 years so "it does not expire" ? people can always go to account and cancel the subscription when they want

**Comment by guerrerotook** [comment]
In the API the expiration time is optional meaning that it can be made not to expire. Could it be a good option also?

**Comment by tiagonmas** [comment]
sounds great

**Comment by tiagonmas** [comment]
I still see it as 5 years. Thought we were changing it to not expire @guerrerotook  ?
![image](https://user-images.githubusercontent.com/42462/194702873-7d14e414-766b-471d-b612-a0e49dc5942c.png)

**Comment by guerrerotook** [comment]
If I don't set the Expiration time, this is the exception from the EasyPay API

`Easypay.Rest.Client.Client.ApiException: 'Error calling SubscriptionPost: {"status":"error","message":["one of these fields must be set: expiration_time and max_captures"]}'`

So, I guess that we have to set a maximum time. Should I change this to 10 years for example?

**Comment by tiagonmas** [comment]
yes, but could be 20 years :)

**Comment by guerrerotook** [comment]
No, EasyPay API say a maximum of 15 years!

**Comment by guerrerotook** [comment]
So, I just created a subscription that expired in 15 years. 

![image](https://user-images.githubusercontent.com/769831/204778779-c893c7d3-88cd-4b3f-9b01-3d14dfd2572f.png)

**Comment by tiagonmas** [comment]
Great!

**Comment by tiagonmas** [comment]
we can close this one, right @guerrerotook ?

**Comment by tiagonmas** [comment]
closing as it is solved
