### ISSUE TITLE
Remove WaitingPayment in subscription details

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#699]
**Is your feature request related to a problem? Please describe.**
The waiting payment is a "implementation detail" that only confuses the customer as there is no action for him.
Can we remove this status from the list ? Why do we have so many of Waiting Payment ? Do we need to keep track of these for subscriptions ?
![image](https://user-images.githubusercontent.com/42462/194703043-a893ef1e-0d8d-4762-acee-f419bdfea06e.png)

**Comment by tiagonmas** [comment]
we should also remove the WaitingPayument transations that relate to subscriptions from donation history
![image](https://user-images.githubusercontent.com/42462/194703200-725176a9-faf3-44f4-a375-b2654b1fa807.png)

**Comment by guerrerotook** [comment]
Did you see that on dev or on prod? The idea is that a waiting payment is something bad for us, because EasyPay couldn't deliver the notification. So let's clear the donation and see why we are not receiving the payments.

**Comment by tiagonmas** [comment]
This is in Prod. Maybe we avoid showing "WaitingPayment" for payments that are older than 24h ?

**Comment by guerrerotook** [comment]
What we can do is, filter pending payments that belong to a subscription because it wasn't process.

**Comment by guerrerotook** [comment]
You can now test this on dev

**Comment by tiagonmas** [comment]
issue #700 is blocking tests alternates "The service is unavailable."  with the exception. Also the changed files are DonationHistory, and not the Details of Subscription ? we also needt o update the Details, right ?

**Comment by guerrerotook** [comment]
Can we close this issue?
