### ISSUE TITLE
/Status endopint throws exceptions

### ISSUE THREAD

**Issue by guerrerotook** [banco-alimentar/alimentestaideia.pt#703]
In Application Insights we can see /status throwing exceptions.

**Comment by guerrerotook** [comment]
The issue with the status is that the test is set to 30 second maximum. And sometimes the request takes longer because the pool is shut down and needs to be executed again. I'm going to increase the timeout for the test to 60 seconds.

FYI @tiagonmas

**Comment by guerrerotook** [comment]
Can we close this issue?

**Comment by tiagonmas** [comment]
I still see some failures once in a while regarding status, but much less. lets close it :)
