### ISSUE TITLE
48 SqlException in last 24h, DonorAddresses cannot be NULL

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#711]
**Describe the bug**
"An error occurred while saving the entity changes. See the inner exception for details. Cannot insert the value NULL into column 'Address1', table 'alimentestaideia.core.dbo.DonorAddresses'; column does not allow nulls. INSERT fails. "

BancoAlimentar.AlimentaEstaIdeia.Repository.PaymentNotificationRepository.AddEmailNotification

As seen in AppInsights

**Comment by guerrerotook** [comment]
I already push some code to try to mitigate this.

**Comment by tiagonmas** [comment]
when /where did you push the code to ? I checked master and dev and last updates where from 2 days ago before this happened ?

**Comment by guerrerotook** [comment]
My last try didn't work. I just this commit to try to solve the issue.

https://github.com/banco-alimentar/alimentestaideia.pt/commit/2c67faa1f17ecc0d1524771bd0ca7d453dbcff9d

I don't know why still complaints that DonorAddress is null when I'm not inserting anything new in the database. Anyway this is an small change.

**Comment by tiagonmas** [comment]
Trying to push this into preprod, but pipeline is failing on [Publish](https://dev.azure.com/BancoAlimentar/Alimentestaideia.pt/_build/results?buildId=1989&view=logs&j=f4a2bb40-7e70-5f50-d570-7d7c5c8ca123&t=9e9e2281-4b2e-5e52-478d-b4058e09432b)

**Comment by guerrerotook** [comment]
Changed the way we are getting those entities when creating the notification. Now instead of getting these values from the database I force to get a WebUser and BasePayment that already exits. Hope this helps solve this issue that still showing in Applicaiton Insights.

**Comment by tiagonmas** [comment]
I dont see any more issues in the last 24h. I think we can close this one. Closing ...
