### ISSUE TITLE
Payment completed but Status is Error

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#735]
**Is your feature request related to a problem? Please describe.**
A user reached out to say that our site shows that a donation was not paid, but it was

```
select * from Donations where id=21539
select * from Payments where Id=22507

```

AppInsights show Thanks page was shown and email sent.

**Comment by tiagonmas** [comment]
we have around 5k in 184 donations that are with error but were paid

`select * from dbo.Donations where ConfirmedPaymentId is not null and PaymentStatus=4`

**Comment by guerrerotook** [comment]
Waiting to test that in developer and in prod to see the effect of the fix.

**Comment by tiagonmas** [comment]
There are still a lot of donations that were paid but status is not 1 (around 73 donations in 2023)
`select * from dbo.Donations where ConfirmedPaymentId is not null and PaymentStatus=4 order by DonationDate desc`

**Comment by tiagonmas** [comment]
same issue as #584

**Comment by tiagonmas** [comment]
Closing this one as we're tracking in #584
