### ISSUE TITLE
EasyPay Subscriptions, expiration time can't exceed the year 2037

### ISSUE THREAD

**Issue by guerrerotook** [banco-alimentar/alimentestaideia.pt#741]
When creating a subscription, we have this exception in AI.

_Error calling SubscriptionPost: {"status":"error","message":["expiration_time: can't exceed year of 2037"]}_

We need to reduce the amount to time where an subscription will expire to avoid this exception.

**Comment by tiagonmas** [comment]
we can close this one now, right @guerrerotook ?
