### ISSUE TITLE
Tests failing: CanUpdatePaymentTransactionToErrorPayment and EasyPayTest

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#759]
Tests are failing, namely:
DonationRepositoryTests.CanUpdatePaymentTransactionToErrorPayment() line 294
 DonationRepositoryTests.EasyPayTest() line 780

Other:
![image](https://github.com/banco-alimentar/alimentestaideia.pt/assets/42462/7dbc2d09-1a38-4dfe-ac08-30a9b6b4e402)

**Comment by guerrerotook** [comment]
This is fix in my branch, will merge to developer.
