### ISSUE TITLE
Update snapshot debugger

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#781]
**Describe the bug**
[A clear and concise description of what the bug is.](https://portal.azure.com/#@bancoalimentar.pt/resource/subscriptions/f1b937fb-ca82-4eb6-a452-77af7a531344/resourceGroups/AlimenteEstaIdeia/providers/microsoft.insights/components/alimentaestaideia-core/failures)

![WhatsApp Image 2024-12-03 at 16 46 54_bbfa5766](https://github.com/user-attachments/assets/ea5116f5-260d-496f-846b-dbdb7f2c3365)

**Comment by guerrerotook** [comment]
The debugger has been updated.
