### ISSUE TITLE
Export donors of a given campaign

### ISSUE THREAD

**Issue by tiagonmas** [banco-alimentar/alimentestaideia.pt#782]
Need to have a backoffice feature that allows to export all emails of people that donated for a specific campaign (after a certain date).
The food bank regularly sends emails to people asking for their donation and they want to exclude those who have already donated.

**Comment by guerrerotook** [comment]
This is ready to test on the UI with the new button Export @tiagonmas 

<img width="872" alt="image" src="https://github.com/user-attachments/assets/4fc4bb83-7bff-4db9-b629-087c3e5fa2e4">

**Comment by tiagonmas** [comment]
works great! thanks
